services:
  - type: web
    name: shopli-marketplace
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
    disk:
      name: sqlite-data
      mountPath: /app/Data
      sizeGB: 1
